In [2]:
import pandas as pd
gas_prices=pd.read_excel("data/raw/avgprice_annual.xlsx")
gas_prices.head()

,"Average Price (Cents/kilowatthour) by State by Provider, 1990-2020",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Year,State,Industry Sector Category,Residential,Commercial,Industrial,Transportation,Other,Total
1,2020,AK,Total Electric Industry,22.57,19.58,15.88,0,NaN,19.82
2,2020,AL,Total Electric Industry,12.58,11.55,5.87,0,NaN,9.84
3,2020,AR,Total Electric Industry,10.41,8.61,5.89,13.32,NaN,8.32
4,2020,AZ,Total Electric Industry,12.27,10.11,6.07,9.38,NaN,10.44

In [3]:
gas_prices=pd.read_excel("data/raw/avgprice_annual.xlsx", skiprows=1)
gas_prices.head()

,Year,State,Industry Sector Category,Residential,Commercial,Industrial,Transportation,Other,Total
0,2020,AK,Total Electric Industry,22.57,19.58,15.88,0.00,NaN,19.82
1,2020,AL,Total Electric Industry,12.58,11.55,5.87,0.00,NaN,9.84
2,2020,AR,Total Electric Industry,10.41,8.61,5.89,13.32,NaN,8.32
3,2020,AZ,Total Electric Industry,12.27,10.11,6.07,9.38,NaN,10.44
4,2020,CA,Total Electric Industry,20.45,17.53,14.27,10.07,NaN,18.00

In [5]:
gas_prices.shape

(4605, 9)

In [6]:
gas_prices.info()

<class 'pandas.DataFrame'>
RangeIndex: 4605 entries, 0 to 4604
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      4605 non-null   int64
 1   State                     4605 non-null   str
 2   Industry Sector Category  4605 non-null   str
 3   Residential               4605 non-null   float64
 4   Commercial                4605 non-null   float64
 5   Industrial                4605 non-null   float64
 6   Transportation            2998 non-null   float64
 7   Other                     1607 non-null   float64
 8   Total                     4605 non-null   float64
dtypes: float64(6), int64(1), str(2)
memory usage: 323.9 KB

In [8]:
is_us=gas_prices["State"]=="US"
is_2020=gas_prices["Year"]==2020
is_total=gas_prices["Industry Sector Category"]=="Total Electric Industry"
us_2020=gas_prices[is_us & is_2020 & is_total]
us_2020

,Year,State,Industry Sector Category,Residential,Commercial,Industrial,Transportation,Other,Total
51,2020,US,Total Electric Industry,13.15,10.59,6.67,9.9,NaN,10.59

In [9]:
us_over_time=gas_prices[is_us & is_total]
us_over_time

,Year,State,Industry Sector Category,Residential,Commercial,Industrial,Transportation,Other,Total
51,2020,US,Total Electric Industry,13.15,10.59,6.67,9.90,NaN,10.59
218,2019,US,Total Electric Industry,13.01,10.68,6.81,9.66,NaN,10.54
385,2018,US,Total Electric Industry,12.87,10.67,6.92,9.70,NaN,10.53
552,2017,US,Total Electric Industry,12.89,10.66,6.88,9.68,NaN,10.48
719,2016,US,Total Electric Industry,12.55,10.43,6.76,9.63,NaN,10.27
886,2015,US,Total Electric Industry,12.65,10.64,6.91,10.09,NaN,10.41
1053,2014,US,Total Electric Industry,12.52,10.74,7.10,10.45,NaN,10.44
1220,2013,US,Total Electric Industry,12.13,10.26,6.89,10.55,NaN,10.07
1384,2012,US,Total Electric Industry,11.88,10.09,6.67,10.21,NaN,9.84
1548,2011,US,Total Electric Industry,11.72,10.24,6.82,10.46,NaN,9.90
1712,2010,US,Total Electric Industry,11.54,10.19,6.77,10.56,NaN,9.83
1879,2009,US,Total Electric Industry,11.51,10.16,6.83,10.66,NaN,9.82
2049,2008,US,Total Electric Industry,11.26,10.26,6.96,10.71,NaN,9.74
2219,2007,US,Total Electric Industry,10.65,9.65,6.39,9.70,NaN,9.13
2386,2006,US,Total Electric Industry,10.40,9.46,6.16,9.54,NaN,8.90
2553,2005,US,Total Electric Industry,9.45,8.67,5.73,8.57,NaN,8.14
2720,2004,US,Total Electric Industry,8.95,8.17,5.25,7.18,NaN,7.61
2888,2003,US,Total Electric Industry,8.72,8.03,5.11,7.54,NaN,7.44
3049,2002,US,Total Electric Industry,8.44,7.89,4.88,NaN,6.75,7.20
3210,2001,US,Total Electric Industry,8.58,7.92,5.05,NaN,7.20,7.29
3374,2000,US,Total Electric Industry,8.24,7.43,4.64,NaN,6.56,6.81
3530,1999,US,Total Electric Industry,8.16,7.26,4.43,NaN,6.35,6.64
3670,1998,US,Total Electric Industry,8.26,7.41,4.48,NaN,6.63,6.74
3798,1997,US,Total Electric Industry,8.43,7.59,4.53,NaN,6.91,6.85
3926,1996,US,Total Electric Industry,8.36,7.64,4.60,NaN,6.91,6.86
4032,1995,US,Total Electric Industry,8.40,7.69,4.66,NaN,6.88,6.89
4136,1994,US,Total Electric Industry,8.38,7.73,4.77,NaN,6.84,6.91
4240,1993,US,Total Electric Industry,8.32,7.74,4.85,NaN,6.88,6.93
4344,1992,US,Total Electric Industry,8.21,7.66,4.83,NaN,6.74,6.82
4448,1991,US,Total Electric Industry,8.04,7.53,4.83,NaN,6.51,6.75
4552,1990,US,Total Electric Industry,7.83,7.34,4.74,NaN,6.40,6.57

In [12]:
us_trend=us_over_time[["Year","Total"]] #double brackets for different columns
us_trend=us_trend.sort_values("Year")
us_trend = us_trend.reset_index(drop=True)
us_trend

    Year  Total
0   1990   6.57
1   1991   6.75
2   1992   6.82
3   1993   6.93
4   1994   6.91
5   1995   6.89
6   1996   6.86
7   1997   6.85
8   1998   6.74
9   1999   6.64
10  2000   6.81
11  2001   7.29
12  2002   7.20
13  2003   7.44
14  2004   7.61
15  2005   8.14
16  2006   8.90
17  2007   9.13
18  2008   9.74
19  2009   9.82
20  2010   9.83
21  2011   9.90
22  2012   9.84
23  2013  10.07
24  2014  10.44
25  2015  10.41
26  2016  10.27
27  2017  10.48
28  2018  10.53
29  2019  10.54
30  2020  10.59

In [13]:
us_trend.describe()

              Year      Total
count    31.000000  31.000000
mean   2005.000000   8.481935
std       9.092121   1.593230
min    1990.000000   6.570000
25%    1997.500000   6.875000
50%    2005.000000   8.140000
75%    2012.500000   9.985000
max    2020.000000  10.590000

In [14]:
not_us=gas_prices["State"] != "US"
states_2020=gas_prices[is_2020 & is_total & not_us]
states_2020
states_2020.shape

(51, 9)

In [22]:
# each state has 1 row
most_expensive=states_2020[["State","Total"]].sort_values("Total",ascending=False)
most_expensive = most_expensive.reset_index(drop=True)
most_expensive.head(10)

  State  Total
0    HI  27.55
1    AK  19.82
2    CT  19.13
3    RI  18.54
4    MA  18.19
5    CA  18.00
6    NH  16.63
7    VT  16.33
8    NY  14.87
9    NJ  13.63

In [23]:
avg_by_year=gas_prices.groupby("Year")["Total"].mean() 
avg_by_year

Year
1990    6.475577
1991    6.648654
1992    6.737500
1993    6.882308
1994    6.891731
1995    6.911923
1996    6.869245
1997    6.702969
1998    6.637812
1999    7.913071
2000    6.189615
2001    6.602744
2002    6.582422
2003    6.601801
2004    6.597143
2005    7.227545
2006    8.006467
2007    8.356287
2008    8.964471
2009    8.808235
2010    8.863713
2011    9.074390
2012    8.997988
2013    9.207195
2014    9.514910
2015    9.463174
2016    9.321317
2017    9.530120
2018    9.720539
2019    9.751198
2020    9.737246
Name: Total, dtype: float64

In [26]:
year_stats=gas_prices.groupby("Year")["Total"].agg(["mean","min","max"])
year_stats

          mean   min     max
Year
1990  6.475577  3.40    9.48
1991  6.648654  3.37   10.17
1992  6.737500  3.43   10.30
1993  6.882308  3.65   10.85
1994  6.891731  4.00   11.32
1995  6.911923  4.07   11.72
1996  6.869245  3.96   12.12
1997  6.702969  3.87   12.49
1998  6.637812  4.02   11.93
1999  7.913071  1.55  151.19
2000  6.189615 -1.52   14.03
2001  6.602744 -1.67   14.05
2002  6.582422  0.35   13.60
2003  6.601801  0.21   14.47
2004  6.597143  0.01   15.70
2005  7.227545  0.19   18.33
2006  8.006467  0.22   20.72
2007  8.356287  0.20   21.29
2008  8.964471  0.00   29.20
2009  8.808235  0.00   21.21
2010  8.863713  0.00   25.12
2011  9.074390  0.33   31.59
2012  8.997988  0.29   34.04
2013  9.207195  0.23   33.26
2014  9.514910  0.22   33.43
2015  9.463174  0.20   26.17
2016  9.321317  0.26   23.87
2017  9.530120  0.33   26.05
2018  9.720539  0.40   29.18
2019  9.751198  0.38   28.72
2020  9.737246  0.63   27.55

In [29]:
avg_by_state=gas_prices.groupby("State")["Total"].mean().sort_values(ascending=False)
avg_by_state.head(10)

State
HI    19.671613
AK    13.393871
CT    11.859098
VT    11.847097
MA    10.946202
NY    10.941679
NH    10.540687
RI    10.406183
CA     9.849389
NJ     9.709843
Name: Total, dtype: float64

In [31]:
clean=gas_prices[gas_prices["Industry Sector Category"]=="Total Electric Industry"]
clean_by_year=clean.groupby("Year")["Total"].mean()
clean_by_year.head()

Year
1990    6.475577
1991    6.648654
1992    6.737500
1993    6.882308
1994    6.891731
Name: Total, dtype: float64

In [32]:
atb=pd.ExcelFile("data/raw/2024_v3_Workbook.xlsx") #need to do this since sheet has multiple subsheets
atb.sheet_names

['Preface and Contents',
 'Financial Definitions',
 'Financial and CRP Inputs',
 'Land-Based Wind',
 'Fixed-Bottom Offshore Wind',
 'Floating Offshore Wind',
 'Distributed Wind',
 'Solar - Utility PV',
 'Solar - PV Dist. Comm',
 'Solar - PV Dist. Res',
 'Solar - CSP',
 'Geothermal',
 'Hydropower',
 'Nuclear',
 'Biopower',
 'Coal_FE',
 'Natural Gas_FE',
 'Natural Gas Fuel Cell_FE',
 'Coal_Retrofits',
 'Natural Gas_Retrofits',
 'Utility-Scale Battery Storage',
 'Commercial Battery Storage',
 'Residential Battery Storage',
 'Utility-Scale PV-Plus-Battery',
 'Pumped Storage Hydropower',
 'PSH One New Res',
 'WACC Calc',
 'Tax Credits',
 'Summary',
 'Summary_CAPEX',
 'Summary_CF',
 'Summary_FCR',
 'Summary_LCOE',
 'Summary_FOM',
 'Summary_VOM',
 'Summary_Fuel',
 'LCOE Range',
 'PV OCC',
 'Program Goals']

In [34]:
capex=pd.read_excel("data/raw/2024_v3_Workbook.xlsx", sheet_name="Summary_CAPEX")
capex.head()

,Key,FinancialCase,CostCase,CRPYears,Technology,TechDetail,DisplayName,2022,2023,2024,...,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050
0,RA3CSSPClass2,R&D,Advanced,30,CSP,Class2,CSP - Class 2,7912.019603,7443.663803,6975.308003,...,3607.070669,3556.334076,3505.597482,3454.860888,3404.124294,3353.387700,3302.651107,3251.914513,3201.177919,3150.441325
1,RM3CSSPClass2,R&D,Moderate,30,CSP,Class2,CSP - Class 2,7912.019603,7570.505287,7228.990972,...,4781.260412,4745.019988,4708.779563,4672.539139,4636.298715,4600.058291,4563.817867,4527.577443,4491.337019,4455.096594
2,RC3CSSPClass2,R&D,Conservative,30,CSP,Class2,CSP - Class 2,7912.019603,7912.019603,7912.019603,...,7912.019603,7912.019603,7912.019603,7912.019603,7912.019603,7912.019603,7912.019603,7912.019603,7912.019603,7912.019603
3,RA3CSSPClass3,R&D,Advanced,30,CSP,Class3,CSP - Class 3,7912.019603,7443.663803,6975.308003,...,3607.070669,3556.334076,3505.597482,3454.860888,3404.124294,3353.387700,3302.651107,3251.914513,3201.177919,3150.441325
4,RM3CSSPClass3,R&D,Moderate,30,CSP,Class3,CSP - Class 3,7912.019603,7570.505287,7228.990972,...,4781.260412,4745.019988,4708.779563,4672.539139,4636.298715,4600.058291,4563.817867,4527.577443,4491.337019,4455.096594

In [36]:
capex.shape
capex.columns.tolist()

['Key',
 'FinancialCase',
 'CostCase',
 'CRPYears',
 'Technology',
 'TechDetail',
 'DisplayName',
 2022,
 2023,
 2024,
 2025,
 2026,
 2027,
 2028,
 2029,
 2030,
 2031,
 2032,
 2033,
 2034,
 2035,
 2036,
 2037,
 2038,
 2039,
 2040,
 2041,
 2042,
 2043,
 2044,
 2045,
 2046,
 2047,
 2048,
 2049,
 2050]

In [38]:
sheets_needed=["Summary_CAPEX","Summary_CF","Summary_FCR","Summary_FOM", "Summary_VOM"]
atb_data=pd.read_excel("data/raw/2024_v3_Workbook.xlsx",sheet_name=sheets_needed)
for name in atb_data:
    print(name,"->", atb_data[name].shape)

Summary_CAPEX -> (526, 36)
Summary_CF -> (420, 36)
Summary_FCR -> (36, 36)
Summary_FOM -> (526, 36)
Summary_VOM -> (526, 36)

In [40]:
capex["FinancialCase"].unique()
capex["CRPYears"].unique()

array([30, 60, 45, '*', 100], dtype=object)

In [41]:
capex["FinancialCase"].value_counts()

FinancialCase
R&D    480
RD      46
Name: count, dtype: int64

In [42]:
# Screening Routine for future
col="FinancialCase"
print("Type:", capex[col].dtype)
print("Number of distinct values:", capex[col].nunique()) #nunique gives count of distinct values
print()
print(capex[col].value_counts(dropna=False)) #value_counts(dropna=False)) lists them with freq incl missing value
capex.isna().sum() #count of NaN in every column at once

Type: str
Number of distinct values: 2

FinancialCase
R&D    480
RD      46
Name: count, dtype: int64

Key               0
FinancialCase     0
CostCase          0
CRPYears          0
Technology        0
TechDetail        0
DisplayName       0
2022             31
2023             31
2024             31
2025             31
2026             31
2027             31
2028             31
2029             31
2030              4
2031              4
2032              4
2033              4
2034              4
2035              0
2036              0
2037              0
2038              0
2039              0
2040              0
2041              0
2042              0
2043              0
2044              0
2045              0
2046              0
2047              0
2048              0
2049              0
2050              0
dtype: int64